### ISSUE TITLE
Prevent asking several time in-sequence consent for webcam usage unless really needed

### ISSUE THREAD

**Issue by johannest** [johannest/webrtc#10]

**Comment by Pasadena** [comment]
@johannest `onUserFound` -method seems to be the one that triggers those extra "permission required" -notifications (because the method re-queries the media stream). 

It seems that streams are connected without the need to re-query the user's current media stream, so the solution to this issue might be to remove the `getUserMedia` -function call from this method.

**Comment by johannest** [comment]
Sounds good

**Comment by johannest** [comment]
Seems to work now
